clear all
close all

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\k68558dj\OneDrive - The University of Manchester\NWPaper\Spectra (fig1)\Belt NW\profile.txt
%
% Auto-generated by MATLAB on 07-Mar-2024 12:49:46

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [4, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Profile", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
profile = readtable("C:\Users\k68558dj\OneDrive - The University of Manchester\NWPaper\Spectra (fig1)\Pattern doped NW\profile.txt", opts);


%% Clear temporary variables
clear opts

x = table2array(profile(:,1));

y = table2array(profile(:,2));


figure(1)
hold on
plot(x,y*1e9, '-','LineWidth', 1.5);
xlabel('X (um)')
ylabel('Height (nm)')
set(gca, 'FontSize', 16, 'LineWidth', 1.5);

